# Generated by Django 4.0.2 on 2022-02-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkhardwaremodel',
            name='asset_type',
            field=models.CharField(choices=[('Wireless Dongle', 'Wireless Dongle'), ('Tape Library', 'Tape Library'), ('Switches', 'Switches'), ('Storage Devices', 'Storage Devices'), ('Print Server', 'Print Server'), ('Network Monitor', 'Network Monitor'), ('Firewall', 'Firewall'), ('Door Access', 'Door Access'), ('Conference Phone', 'Conference Phone'), ('CCTV DVR', 'CCTV DVR'), ('CCTV Camera', 'CCTV Camera'), ('AP', 'AP'), ('Server', 'Server')], max_length=1000),
        ),
    ]
