# Generated by Django 4.0.2 on 2022-02-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0002_alter_networkhardwaremodel_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_DOP_year',
        ),
    ]
