# Generated by Django 4.0.2 on 2022-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_remove_software_software_dop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='software_quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_quantity_left',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
