# Generated by Django 4.0.2 on 2022-04-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_laptop_cdunlock_laptop_usbunlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='testdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(blank=True, max_length=100, null=True)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
