# Generated by Django 4.0.2 on 2022-04-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='laptop',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
