# Generated by Django 4.0.2 on 2022-06-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_computer_qrcode_image_laptop_qrcode_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testdb',
        ),
    ]
